---
# tasks file for php4docker
- name: copy php4docker config
  ansible.builtin.copy:
    dest: /home/ubuntu/docker/
    src: .env
    owner: ubuntu

- name: copy php4docker config
  ansible.builtin.copy:
    dest: /home/ubuntu/docker/
    src: docker-compose.yml
    owner: ubuntu

- name: create directory db/mariadb-init
  ansible.builtin.file:
    path: /home/ubuntu/docker/db/mariadb-init
    state: directory
    owner: ubuntu
    mode: "0755"

- name: copy mysql init config
  ansible.builtin.template:
    dest: /home/ubuntu/docker/db/mariadb-init/init.sql
    src: init.sql.j2

- name: create directory php/conf.d
  ansible.builtin.file:
    path: /home/ubuntu/docker/php/conf.d
    state: directory
    owner: ubuntu
    mode: "0755"

- name: unpack php config
  ansible.builtin.unarchive:
    dest: /home/ubuntu/docker/php/conf.d
    src: php.tar.gz

- name: chown php
  ansible.builtin.file:
    path: /home/ubuntu/docker/php
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: chown html
  ansible.builtin.file:
    path: /home/ubuntu/docker/html
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu


- name: start docker compose php4docker
  ansible.builtin.shell: docker-compose up -d
  args:
    chdir: /home/ubuntu/docker
