---
# tasks file for dvwa
- name: create dir dvwa
  ansible.builtin.file:
    path: /home/ubuntu/docker/html/public/dvwa
    state: directory
    mode: '0755'

- name: install unzip
  ansible.builtin.apt:
    name: zip
    state: present
    update_cache: yes

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://github.com/ethicalhack3r/DVWA/archive/master.zip
    dest: /home/ubuntu/docker/html/public/dvwa
    remote_src: yes
    owner: ubuntu

- name: mv DVWA-master to dvwa
  ansible.builtin.shell: mv /home/ubuntu/docker/html/public/dvwa/DVWA-master/* /home/ubuntu/docker/html/public/dvwa/ && rm -rf /home/ubuntu/docker/html/public/dvwa/DVWA-master/

- name: configure dvwa
  ansible.builtin.template:
    dest: /home/ubuntu/docker/html/public/dvwa/config/config.inc.php
    src: config.inc.php.j2


